version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file: .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
